app/models/ann_model.py
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.callbacks import Callback
from keras.layers import Dense, Dropout, BatchNormalization
import matplotlib.pyplot as plt
import numpy as np
from sqlalchemy import create_engine, insert, MetaData, Table
import json

class PrintEvery50Epochs(Callback):
    def on_epoch_end(self, epoch, logs=None):
        if (epoch + 1) % 50 == 0 or epoch == 0:
           print(f"Epoch {epoch + 1}: loss - {logs['loss']:.4f}, mae - {logs['mae']:.4f}, val_loss - {logs['val_loss']:.4f}, val_mae - {logs['val_mae']:.4f}")

def get_db_url():
    with open('config.json') as config_file:
        config = json.load(config_file)
    return config['db_url']

db_url = get_db_url()
engine = create_engine(db_url)
predictions_ann = Table('predictions_ann', MetaData(), autoload_with=engine)

def load_data_from_db():
   sql_query = 'SELECT * FROM fuelsources'
   return pd.read_sql_query(sql_query, engine)

def save_predictions_to_db(actuals, predictions, years, actuals_train, predictions_train, years_train):
    df = pd.DataFrame({
        'actual': actuals, 
        'prediction': predictions, 
        'year': years,
        'actual': actuals_train,
        'prediction': predictions_train,
        'year': years_train})    
    df.to_sql('predictions_ann', con=engine, if_exists='replace', index=False)

def train_ann_model():
    """
    Trains an Artificial Neural Network (ANN) model using the given dataset.
    """

    # Loading the Data
    train_data = load_data_from_db()

    print(train_data.head())
    
    features = ['year', 'coalprice','oilprice', 'gasprice', 'nuclearprice', 'hydroprice', 'windsolarprice', 'cokebreezeprice']
    X = train_data[features]  # Your input features
    y = train_data['avgprice']  # Your target variable

    # Splitting the dataset into the Training set and Test set
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 32)

    # Extracting the years from the dataset
    years_test = X_test['year'].values
    years_train = X_train['year'].values

    # Feature Scaling
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)

    # Initialising the ANN 
    model = Sequential([
        Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
        BatchNormalization(),
        Dropout(0.2),
        Dense(128, activation='relu'),
        Dropout(0.2),
        Dense(64, activation='relu'),
        Dense(1, activation='linear')
    ])

    #Print Model Summary 
    print(model.summary())
    # Compiling the ANN
    model.compile(optimizer=tf.keras.optimizers.Adamax(learning_rate=0.05,beta_1=0.9, beta_2=0.999, epsilon=1e-07,), loss='mean_squared_error', metrics=['mae'])
    # Fitting the ANN to the Training set
    history = model.fit(X_train, y_train, validation_split=0.2, epochs=500, batch_size=128, callbacks=[PrintEvery50Epochs()], verbose=0)
    # Evaluating the ANN
    model.evaluate(X_test, y_test)
    # Predicting the Test set results
    predictions_test = model.predict(X_test)
    preditctions_train = model.predict(X_train)
    # Flatten the predictions and actual values to 1D array
    predictions_test = predictions_test.flatten()
    preditctions_train = preditctions_train.flatten()

    actual_values_test = y_test.to_numpy()
    actual_values_train = y_train.to_numpy()

    # Save the predictions to the database
    save_predictions_to_db(actual_values_test, predictions_test, years_test, actual_values_train, preditctions_train, years_train)

    """
    print(f"Number of predictions: {len(predictions_test)}")
    print(f"Number of actual values: {len(actual_values_test)}")
    print(f"Number of years: {len(years_test)}")
    print(f"Number of predictions: {len(preditctions_train)}")
    print(f"Number of actual values: {len(actual_values_train)}")
    print(f"Number of years: {len(years_train)}")
    """

    epochs = history.epoch
    indices = [i for i in epochs if i % 50 == 0 or i == epochs[0]]

    # Print the test predictions and actual values
    print("Prediction vs Actual")
    for i in range(len(predictions_test)):
        print(f"Prediction: {predictions_test[i]:.4f}, Actual: {actual_values_test[i]:.4f}")
    # Print the train predictions and actual values
    print("Prediction vs Actual")
    for i in range(len(preditctions_train)):
        print(f"Prediction: {preditctions_train[i]:.4f}, Actual: {actual_values_train[i]:.4f}")

    # Print the test loss and test MAE
    test_loss, test_mae = model.evaluate(X_test, y_test)
    print(f"Test Loss: {test_loss}, Test MAE: {test_mae}")

    def plot_act_vs_predicted(predicted, actual, title):
        plt.figure(figsize=(12, 6))
        plt.plot(predicted, label='Predictions', color='red', linestyle='--', marker='x')
        plt.plot(actual, label='Actual', color='blue', linestyle='--', marker='o')
        plt.title(f'Predictions vs Actual Values ANN Model ({title})')
        plt.legend()
        plt.show()

        # Plot training & validation loss values every 50 epochs
    plt.figure(figsize=(12, 6))
    plt.plot([history.history['loss'][i] for i in indices], label='Loss (training data)', marker='o')
    plt.plot([history.history['val_loss'][i] for i in indices], label='Loss (validation data)', marker='o')
    plt.title('Model MSE Loss Every 50 Epochs')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.xticks(range(len(indices)), labels=[str(i+1) for i in indices])  # Set x-ticks to show epoch numbers
    plt.legend(loc="upper right")
    plt.grid(True)
    plt.show()

    plt.figure(figsize=(12, 6))
    plt.plot([history.history['mae'][i] for i in indices], label='MAE (training data)', marker='o')
    plt.plot([history.history['val_mae'][i] for i in indices], label='MAE (validation data)', marker='o')
    plt.title('Model MAE Every 50 Epochs')
    plt.ylabel('MAE')
    plt.xlabel('Epoch')
    plt.xticks(range(len(indices)), labels=[str(i+1) for i in indices])  # Set x-ticks to show epoch numbers
    plt.legend(loc="upper right")
    plt.grid(True)
    plt.show()

    plot_act_vs_predicted(predictions_test, actual_values_test, "Test Data")
    plot_act_vs_predicted(preditctions_train, actual_values_train, "Train Data")
train_ann_model()

app/models/ann_model_p.py
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.callbacks import Callback
from keras.layers import Dense, Dropout, BatchNormalization
import matplotlib.pyplot as plt
import numpy as np
from sqlalchemy import create_engine, insert, MetaData, Table
import json
import keras_tuner as kt

# Callback to print training progress every 50 epochs
class PrintEvery50Epochs(Callback):
    def on_epoch_end(self, epoch, logs=None):
        if (epoch + 1) % 50 == 0 or epoch == 0:
            print(f"Epoch {epoch + 1}: loss - {logs['loss']:.4f}, mae - {logs['mae']:.4f}, val_loss - {logs['val_loss']:.4f}, val_mae - {logs['val_mae']:.4f}")

# Function to retrieve database URL from config file
def get_db_url():
    with open('config.json') as config_file:
        config = json.load(config_file)
    return config['db_url']

# Creating a database engine
db_url = get_db_url()
engine = create_engine(db_url)

# Function to load data from the database
def load_data_from_db():
    sql_query = 'SELECT * FROM fuelsources'
    return pd.read_sql_query(sql_query, engine)

# Function to save predictions to the database
def save_predictions_to_db(actuals, predictions, years, actuals_train, predictions_train, years_train):
    test_df = pd.DataFrame({
        'type': 'test',
        'actual': actuals,
        'prediction': predictions,
        'year': years,
    })
    train_df = pd.DataFrame({
        'type': 'train',
        'actual': actuals_train,
        'prediction': predictions_train,
        'year': years_train})

    combined_df = pd.concat([test_df, train_df])
    combined_df.to_sql('predictions_ann', con=engine, if_exists='replace', index=False)
    print("Data saved to database successfully.")

# Function to plot actual vs predicted values
def plot_act_vs_predicted(predicted, actual, title):
    plt.figure(figsize=(12, 6))
    plt.plot(predicted, label='Predictions', color='red', linestyle='--', marker='x')
    plt.plot(actual, label='Actual', color='blue', linestyle='--', marker='o')
    plt.title(f'Predictions vs Actual Values ANN Model ({title})')
    plt.legend()
    plt.show()
    
    
def train_ann_model():
    """
    Trains an Artificial Neural Network (ANN) model using the given dataset.
    """

    # Loading the Data 
    train_data = load_data_from_db()

    print(train_data.head())
    
    features = ['year', 'coalprice','oilprice', 'gasprice', 'nuclearprice', 'hydroprice', 'windsolarprice', 'cokebreezeprice']
    x = train_data[features]  # Your input features
    y = train_data['avgprice']  # Your target variable

    # Splitting the dataset into the Training set and Test set
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0, shuffle=True)

    # Extracting the years from the dataset
    years_test = x_test['year'].values
    years_train = x_train['year'].values

    # Feature Scaling
    sc = StandardScaler()
    x_train_scaled = sc.fit_transform(x_train)
    x_test_scaled = sc.transform(x_test)

    # Initialising the ANN 
    model = Sequential([
        Dense(64, activation='relu', input_shape=(x_train_scaled.shape[1],)),
        BatchNormalization(),
        Dropout(0.2),
        Dense(128, activation='relu'),
        Dropout(0.2),
        Dense(64, activation='relu'),
        Dense(1, activation='linear')
    ])

    #Print Model Summary 
    print(model.summary())
    # Compiling the ANN
    model.compile(optimizer=tf.keras.optimizers.Adamax(learning_rate=0.05,beta_1=0.9, beta_2=0.999, epsilon=1e-07,), loss='mean_squared_error', metrics=['mae'])
    # Fitting the ANN to the Training set
    history = model.fit(x_train_scaled, y_train, validation_split=0.2, epochs=500, batch_size=128, callbacks=[PrintEvery50Epochs()], verbose=0)
    # Evaluating the ANN
    model.evaluate(x_test_scaled, y_test)
    # Predicting the Test set results
    predictions_test = model.predict(x_test_scaled)
    preditctions_train = model.predict(x_train_scaled)
    # Flatten the predictions and actual values to 1D array
    predictions_test = predictions_test.flatten()
    preditctions_train = preditctions_train.flatten()

    actual_values_test = y_test.to_numpy()
    actual_values_train = y_train.to_numpy()

    # Save the predictions to the database
    save_predictions_to_db(actual_values_test, predictions_test, years_test, actual_values_train, preditctions_train, years_train)

    epochs = history.epoch
    indices = [i for i in epochs if i % 50 == 0 or i == epochs[0]]

        # Plot training & validation loss values every 50 epochs
    plt.figure(figsize=(12, 6))
    plt.plot([history.history['loss'][i] for i in indices], label='Loss (training data)', marker='o')
    plt.plot([history.history['val_loss'][i] for i in indices], label='Loss (validation data)', marker='o')
    plt.title('Model MSE Loss Every 50 Epochs')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.xticks(range(len(indices)), labels=[str(i+1) for i in indices])  # Set x-ticks to show epoch numbers
    plt.legend(loc="upper right")
    plt.grid(True)
    plt.show()

    plt.figure(figsize=(12, 6))
    plt.plot([history.history['mae'][i] for i in indices], label='MAE (training data)', marker='o')
    plt.plot([history.history['val_mae'][i] for i in indices], label='MAE (validation data)', marker='o')
    plt.title('Model MAE Every 50 Epochs')
    plt.ylabel('MAE')
    plt.xlabel('Epoch')
    plt.xticks(range(len(indices)), labels=[str(i+1) for i in indices])  # Set x-ticks to show epoch numbers
    plt.legend(loc="upper right")
    plt.grid(True)
    plt.show()

    plot_act_vs_predicted(predictions_test, actual_values_test, "Test Data")
    plot_act_vs_predicted(preditctions_train, actual_values_train, "Train Data")

       # Print the test predictions and actual values
    print("Prediction vs Actual")
    for i in range(len(predictions_test)):
        print(f"Prediction: {predictions_test[i]:.4f}, Actual: {actual_values_test[i]:.4f}")
    # Print the train predictions and actual values
    print("Prediction vs Actual")
    for i in range(len(preditctions_train)):
        print(f"Prediction: {preditctions_train[i]:.4f}, Actual: {actual_values_train[i]:.4f}")

     # Print the test loss and test MAE
    test_loss, test_mae = model.evaluate(x_test_scaled, y_test)
    print(f"Test Loss: {test_loss}, Test MAE: {test_mae}")
train_ann_model()

app/routes.py
from flask import render_template, Blueprint, request, jsonify
from flask import Flask
from sqlalchemy import create_engine, insert, MetaData, Table
import pandas as pd
import json


def get_db_url():
    with open('config.json') as config_file:
        config = json.load(config_file)
    return config['db_url']

db_url = get_db_url()
engine = create_engine(db_url)
predictions_ann = Table('predictions_ann', MetaData(), autoload_with=engine)


main_blueprint = Blueprint('main', __name__)

@main_blueprint.route('/api/data/ann', methods=['GET'])
def get_data_ann():
    df = pd.read_sql_query('SELECT * FROM predictions_ann ORDER BY year ASC', engine)

    response_data = {
        'labels': df['year'].tolist(),
        'datasets': [
            {
                'label': 'Actual',
                'data': df['actual'].tolist(),
                'fill': False,
                'borderColor': '#FF6384',
                'backgroundColor': '#FF6384'
            },
            {
                'label': 'Prediction',
                'data': df['prediction'].tolist(),
                'fill': False,
                'borderColor': '#36A2EB',
                'backgroundColor': '#36A2EB'
            }
        ]
}
    return jsonify(response_data)

@main_blueprint.route('/api/data/svm', methods=['GET'])
def get_data_svm():
    df = pd.read_sql_query('SELECT * FROM svm_prediction ORDER BY year ASC', engine)

    response_data = {
        'labels': df['year'].tolist(),
        'datasets': [
            {
                'label': 'Actual',
                'data': df['actual'].tolist(),
                'fill': False,
                'borderColor': '#FF6384',
                'backgroundColor': '#FF6384'
            },
            {
                'label': 'Prediction',
                'data': df['prediction'].tolist(),
                'fill': False,
                'borderColor': '#36A2EB',
                'backgroundColor': '#36A2EB'
            }
        ]
}
    return jsonify(response_data)

@main_blueprint.route('/api/costs', methods=['GET'])
def calculate_costs():
    model = request.args.get('model', 'ann')
    year = request.args.get('year', type=int)
    kwh = request.args.get('kwh', type=float)  # Ensure kwh is obtained as a float

    # Assuming `fetch_prediction_data` returns the price per kWh
    predicted_price = fetch_prediction_data(year, model)
    if predicted_price is None:
        return jsonify({'error': 'No data available for selected year and model'}), 404

    if kwh is None or kwh < 0:
        return jsonify({'error': 'Invalid kWh value. Please provide a positive number.'}), 400

    cost = (predicted_price * kwh)/100  # Calculate total cost based on kWh input and model prediction
    return jsonify({'cost': cost})

def fetch_prediction_data(year, model):
    table = 'predictions_ann' if model.lower() == 'ann' else 'svm_prediction'
    query = f"SELECT prediction FROM {table} WHERE year = {year}"
    df = pd.read_sql_query(query, engine)
    return df['prediction'].iloc[0] if not df.empty else None



@main_blueprint.route('/')
def home():
    return render_template('home.html')

@main_blueprint.route('/about/')
def about():
    return render_template('about.html')

@main_blueprint.route('/contact/')
def contact():
    return render_template('contact.html')

@main_blueprint.route('/models/')
def models():
    return render_template('models.html')

app/templates/about.html
{% extends "layout.html" %}
{% block title %}
About
{% endblock %}
{% block content %}
<p>About page for Cormacs Final Year Project</p>
{% endblock %}

app/templates/contact.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% extends "layout.html" %}
{% block title %}
Contact
{% endblock %}
{% block content %}
<div class="contact-info">
    <h2>Contact me</h2>
    <p>Contact page for Cormacs Final Year Project</p>
    <ul class="contact-list">
        <li><i class="fab fa-linkedin"></i> <a href="https://www.linkedin.com/in/cormac-duffy/" target="_blank">Cormac Duffy</a></li>
        <li><i class="fab fa-github"></i> <a href="https://github.com/cormacduffy25" target="_blank">cormacduffy25</a></li>
        <li><i class="fas fa-envelope"></i> <a href="mailto:cormacduffy648@hotmail.com">cormacduffy648@hotmail.com</a></li>
    </ul>
</div>
{% endblock %}

app/templates/home.html
{% extends "layout.html" %}
{% block title %}
Home
{% endblock %}
{% block content %}
<p>Home page for Cormacs Final Year Project</p>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='site.css') }}"/>
    </head>

    <body>

<div class="navbar">
    <a href = "{{ url_for('main.home') }}" class ="navbar-item">Home</a>
    <a href = "{{ url_for('main.about') }}" class ="navbar-item">About</a>
    <a href = "{{ url_for('main.contact') }}" class ="navbar-item">Contact</a>
    <a href = "{{ url_for('main.models') }}" class ="navbar-item">Models</a>
</div>   

<div class = "body-content">
    {% block content %}
    {% endblock %}
    <hr/>
    <footer>
    <p> &copy; 2024</p>
    </footer>
</div>
</body>
</html>

app/templates/models.html
{% extends "layout.html" %}
{% block title %}
Models
{% endblock %}
{% block content %}
<p>Models page for Cormacs Final Year Project</p>

<div class="charts-container">
    <div class="chart" id="annChartContainer">
        <canvas id="annChart" width="800" height="400"></canvas>
    </div>
    <div class="chart" id="svmChartContainer">
        <canvas id="svmChart" width="800" height="400"></canvas>
    </div>
</div>
<div class="calculator">
    <div class="input-group">
        <label for="kWh">Enter the your yearly average household kWh:</label>
        <input type="number" id="kWh" placeholder="kWh" min="0">
    </div>
    <div class="input-group">
        <label for="yearSelect">Select Year:</label>
        <select id="yearSelect">
            <option value="2022">2022</option>
            <option value="2023">2023 (Forecasted Data)</option>
            <option value="2024">2024 (Forecasted Data)</option>
            <option value="2025">2025 (Forecasted Data)</option>
        </select>
    </div>
    <div class="input-group">
        <label for="modelSelect">Choose Model:</label>
        <select id="modelSelect">
            <option value="SVM">SVM</option>
            <option value="ANN">ANN</option>
        </select>
    </div>
    <button onclick="performCalculation()">Calculate</button>
    <div id="output"></div>
</div>


<script>
    function performCalculation() {
        const kwhInput = document.getElementById('kWh'); // Get the input element
        const kwh = parseFloat(kwhInput.value); // Directly convert the input's value to a number

        // Validate input
        if (kwh < 0 || isNaN(kwh)) {
            document.getElementById('output').innerText = 'Invalid input. Please enter a positive number.';
            return; // Important to return here to stop further execution
        }

        const year = document.getElementById('yearSelect').value;
        const model = document.getElementById('modelSelect').value;
        const url = `/api/costs?model=${model}&year=${year}&kwh=${kwh}`;

        fetch(url)
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.json();
            })
            .then(data => {
                // Make sure your API is returning a cost value in the response
                if (data && data.cost !== undefined) {
                    document.getElementById('output').innerText = `Estimated Yearly Cost: ${data.cost.toFixed(2)} GBP`;
                } else {
                    // Handle cases where the cost might not be returned in the response
                    document.getElementById('output').innerText = 'No cost data was returned from the API.';
                }
            })
            .catch(error => {
                console.error('Failed to fetch data:', error);
                document.getElementById('output').innerText = 'Error calculating costs.';
            });
    }
</script>


<script>
    // This function processes datasets to replace zero values with null
    function processChartData(datasets) {
        return datasets.map(dataset => {
            return {
                ...dataset,
                data: dataset.data.map(value => value === 0 ? null : value)
            };
        });
    }
</script>

<script>
function setupChart(ctx, data, titleText) {
    const processedDatasets = processChartData(data.datasets);
    return new Chart(ctx, {
        type: 'line',
        data: {
            labels: data.labels,
            datasets: processedDatasets
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                title: {
                    display: true,
                    text: titleText
                }
            },
            scales: {
                y: {
                    beginAtZero: true,
                    title: {
                        display: true,
                        text: 'Electric Pricing pence/kWh'
                    }
                },
                x: {
                    title: {
                        display: true,
                        text: 'Year'
                    }
                }
            },
            spanGaps: true
        }
    });
}

function fetchDataAndCreateChart(endpoint, chartId, title) {
    fetch(endpoint)
    .then(response => response.json())
    .then(data => setupChart(document.getElementById(chartId).getContext('2d'), data, title))
    .catch(error => {
        console.error('Error loading the data: ', error);
        document.getElementById(chartId).parentElement.innerHTML = '<p>Error loading data!</p>';
    });
}

document.addEventListener('DOMContentLoaded', function() {
    fetchDataAndCreateChart('/api/data/ann', 'annChart', 'ANN Model Performance');
    fetchDataAndCreateChart('/api/data/svm', 'svmChart', 'SVM Model Performance');
});
</script>
{% endblock %}